services:

  api:
    #harman0701 = Docker Hub username/namespace.
    # It tells Docker which Docker Hub repository this image belongs to.
    # This allows the production server to pull the image from
    # your Docker Hub account.
    image: harman0701/nestjs-basic-auth:latest # writing image name
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-basic-auth
    restart: unless-stopped
    ports:
      - '127.0.0.1:5000:5000'
    env_file:
      - .env
    environment:
      NODE_ENV: production